using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UetMap
{
    internal enum Locations
    {
        Gate3 = 1,
        ElectricalDepartment,
        Library,
        ComputerScience,
        CivilDepartment,
        TransportationDepartment,
        GSSC,
        ComputerEngineering,
        MathematicsDepartment,
        KICS,
        MechanicalDepartment,
        MechatronicsDepartment,
        Auditorium,
        PhysicsDepartment,
        Gate5,
        KhadijaHall,
        PowerHouse,
        FacultyHostel,
        GirlsGround,
        NewGirlsHostel,
        MiningDepartment,
        Postoffice,
        StaffColony,
        ChemicalDepartment,
        GeologicalDepartment,
        MetallurgicalDepartment,
        InstituteofDataScience,
        JJCricketGround,
        FootballGround,
        BholaCafe,
        SecurityOffice,
        SportsComplex,
        BColony,
        MumtazHall,
        QuaideAzamHall,
        LiaquatHall,
        QCanteen,
        IqbalHall,
        SirSyedHall,
        ShoppingCentre,
        ZubairHall,
        MBQHall,
        EdhiHall,
        SSC,
        TariqHall,
        KhalidHall,
        AnnexeGround,
        AutomotiveDepartment,
        Annexe,
        WorkshopAndChemistryDepartment,
        IBM,
        JamiaMosque,
        TransportOffice,
        ArchitectureEngineering,
        IslamicStudies,
        AdminOffice,
        HBL,
        VCOffice,
        Lalazar,
        CRP,
        ArchitectureAndDesign,
        PolymerDepartment,
        ColonyGate2
    }

}
